// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PentaHub.Infrastructure.Data;

#nullable disable

namespace PentaHub.Infrastructure.Migrations
{
    [DbContext(typeof(PentaHubDbContext))]
    [Migration("20260327210118_AddSprintManagement")]
    partial class AddSprintManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("PentaHub.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerEvaluation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluationFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBillable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrivacyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("IX_Projects_ContactId");

                    b.HasIndex("ProjectManagerId")
                        .HasDatabaseName("IX_Projects_ProjectManagerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Projects_Status");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "Yazılım",
                            Description = "Acme firmasının dijital dönüşüm süreçlerinin yönetimi",
                            EndDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "Acme Dijital Dönüşüm Projesi",
                            PrivacyLevel = 2,
                            ProjectManagerId = 1,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "Satış",
                            Description = "Müşteri ilişkileri yönetimi sistemi kurulumu",
                            EndDate = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "CRM İmplementasyon",
                            PrivacyLevel = 1,
                            ProjectManagerId = 2,
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "Yazılım",
                            Description = "iOS ve Android platformları için mobil uygulama",
                            EndDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "Mobil Uygulama Geliştirme",
                            PrivacyLevel = 0,
                            ProjectManagerId = 1,
                            StartDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "IT",
                            Description = "Mevcut ERP sistemi ile e-ticaret platformu entegrasyonu",
                            EndDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "E-Ticaret Platform Entegrasyonu",
                            PrivacyLevel = 1,
                            ProjectManagerId = 5,
                            StartDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "İK",
                            Description = "Şirket içi eğitim ve sertifikasyon platformu",
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = false,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "İç Eğitim Portalı",
                            PrivacyLevel = 1,
                            ProjectManagerId = 5,
                            StartDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "IT",
                            Description = "Legacy veri ambarının bulut tabanlı çözüme taşınması",
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = false,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "Veri Ambarı Modernizasyonu",
                            PrivacyLevel = 0,
                            ProjectManagerId = 4,
                            StartDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "Yazılım",
                            Description = "Müşteri self-servis portalının yeniden tasarlanması",
                            EndDate = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "Müşteri Portalı Yenileme",
                            PrivacyLevel = 2,
                            ProjectManagerId = 2,
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "Pazarlama",
                            Description = "Marketing automation araçlarının entegrasyonu ve kampanya yönetimi",
                            EndDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = false,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "Pazarlama Otomasyon Projesi",
                            PrivacyLevel = 1,
                            ProjectManagerId = 5,
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        });
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BusinessDaysOnly")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MilestoneId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PlannedHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RemainingHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SpentHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("IX_Tasks_AssigneeId");

                    b.HasIndex("ParentTaskId")
                        .HasDatabaseName("IX_Tasks_ParentTaskId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Tasks_ProjectId");

                    b.HasIndex("SprintId")
                        .HasDatabaseName("IX_Tasks_SprintId");

                    b.HasIndex("StageId")
                        .HasDatabaseName("IX_Tasks_StageId");

                    b.HasIndex("TaskNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Tasks_TaskNumber");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssigneeId = 1,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            PlannedHours = 16m,
                            Priority = 3,
                            ProgressPercent = 0,
                            ProjectId = 1,
                            RemainingHours = 16m,
                            SortOrder = 1,
                            SpentHours = 0m,
                            SprintId = 1,
                            StageId = 1,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0001",
                            Title = "CRM Modülünün Konfigürasyonu"
                        },
                        new
                        {
                            Id = 2,
                            AssigneeId = 2,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            PlannedHours = 8m,
                            Priority = 2,
                            ProgressPercent = 0,
                            ProjectId = 1,
                            RemainingHours = 8m,
                            SortOrder = 2,
                            SpentHours = 0m,
                            SprintId = 1,
                            StageId = 1,
                            StartDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0002",
                            Title = "Kullanıcı Rol ve Yetkileri Tanımlama"
                        },
                        new
                        {
                            Id = 3,
                            AssigneeId = 3,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            PlannedHours = 24m,
                            Priority = 4,
                            ProgressPercent = 0,
                            ProjectId = 1,
                            RemainingHours = 24m,
                            SortOrder = 3,
                            SpentHours = 0m,
                            SprintId = 1,
                            StageId = 1,
                            StartDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0003",
                            Title = "Veri Migrasyon Planı"
                        },
                        new
                        {
                            Id = 4,
                            AssigneeId = 4,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            PlannedHours = 40m,
                            Priority = 3,
                            ProgressPercent = 20,
                            ProjectId = 1,
                            RemainingHours = 32m,
                            SortOrder = 1,
                            SpentHours = 8m,
                            SprintId = 1,
                            StageId = 2,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0004",
                            Title = "API Entegrasyon Geliştirme"
                        },
                        new
                        {
                            Id = 5,
                            AssigneeId = 5,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = false,
                            IsDeleted = false,
                            PlannedHours = 20m,
                            Priority = 2,
                            ProgressPercent = 20,
                            ProjectId = 1,
                            RemainingHours = 16m,
                            SortOrder = 2,
                            SpentHours = 4m,
                            SprintId = 1,
                            StageId = 2,
                            StartDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0005",
                            Title = "UI/UX Tasarım Revizyonu"
                        },
                        new
                        {
                            Id = 6,
                            AssigneeId = 1,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            PlannedHours = 16m,
                            Priority = 4,
                            ProgressPercent = 38,
                            ProjectId = 1,
                            RemainingHours = 10m,
                            SortOrder = 3,
                            SpentHours = 6m,
                            SprintId = 2,
                            StageId = 2,
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0006",
                            Title = "Güvenlik Denetimi"
                        },
                        new
                        {
                            Id = 7,
                            AssigneeId = 2,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            PlannedHours = 24m,
                            Priority = 2,
                            ProgressPercent = 50,
                            ProjectId = 1,
                            RemainingHours = 12m,
                            SortOrder = 1,
                            SpentHours = 12m,
                            SprintId = 2,
                            StageId = 3,
                            StartDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0007",
                            Title = "Performans Testleri"
                        },
                        new
                        {
                            Id = 8,
                            AssigneeId = 3,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            PlannedHours = 32m,
                            Priority = 3,
                            ProgressPercent = 50,
                            ProjectId = 1,
                            RemainingHours = 16m,
                            SortOrder = 2,
                            SpentHours = 16m,
                            SprintId = 2,
                            StageId = 3,
                            StartDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0008",
                            Title = "Raporlama Modülü"
                        },
                        new
                        {
                            Id = 9,
                            AssigneeId = 4,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = false,
                            IsDeleted = false,
                            PlannedHours = 48m,
                            Priority = 1,
                            ProgressPercent = 42,
                            ProjectId = 1,
                            RemainingHours = 28m,
                            SortOrder = 3,
                            SpentHours = 20m,
                            SprintId = 2,
                            StageId = 3,
                            StartDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0009",
                            Title = "Mobil Arayüz Geliştirme"
                        },
                        new
                        {
                            Id = 10,
                            AssigneeId = 5,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            PlannedHours = 16m,
                            Priority = 2,
                            ProgressPercent = 63,
                            ProjectId = 1,
                            RemainingHours = 6m,
                            SortOrder = 4,
                            SpentHours = 10m,
                            SprintId = 2,
                            StageId = 3,
                            StartDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0010",
                            Title = "Veritabanı Optimizasyonu"
                        },
                        new
                        {
                            Id = 11,
                            AssigneeId = 1,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            PlannedHours = 20m,
                            Priority = 3,
                            ProgressPercent = 80,
                            ProjectId = 1,
                            RemainingHours = 4m,
                            SortOrder = 1,
                            SpentHours = 16m,
                            StageId = 4,
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0011",
                            Title = "Entegrasyon Testleri"
                        },
                        new
                        {
                            Id = 12,
                            AssigneeId = 2,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            PlannedHours = 16m,
                            Priority = 3,
                            ProgressPercent = 75,
                            ProjectId = 1,
                            RemainingHours = 4m,
                            SortOrder = 2,
                            SpentHours = 12m,
                            StageId = 4,
                            StartDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0012",
                            Title = "Kullanıcı Kabul Testleri"
                        },
                        new
                        {
                            Id = 13,
                            AssigneeId = 3,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = false,
                            IsDeleted = false,
                            PlannedHours = 12m,
                            Priority = 4,
                            ProgressPercent = 67,
                            ProjectId = 1,
                            RemainingHours = 4m,
                            SortOrder = 3,
                            SpentHours = 8m,
                            StageId = 4,
                            StartDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0013",
                            Title = "Go-Live Planlaması"
                        },
                        new
                        {
                            Id = 14,
                            AssigneeId = 4,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = false,
                            IsDeleted = false,
                            PlannedHours = 12m,
                            Priority = 1,
                            ProgressPercent = 100,
                            ProjectId = 1,
                            RemainingHours = 0m,
                            SortOrder = 1,
                            SpentHours = 12m,
                            StageId = 5,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0014",
                            Title = "Eğitim Materyalleri Hazırlama"
                        },
                        new
                        {
                            Id = 15,
                            AssigneeId = 5,
                            BusinessDaysOnly = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = false,
                            IsDeleted = false,
                            PlannedHours = 8m,
                            Priority = 0,
                            ProgressPercent = 100,
                            ProjectId = 1,
                            RemainingHours = 0m,
                            SortOrder = 2,
                            SpentHours = 8m,
                            StageId = 5,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            TaskNumber = "T0015",
                            Title = "Dokümantasyon"
                        });
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Sprints_ProjectId");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_Sprints_State");

                    b.ToTable("Sprints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Goal = "Temel altyapı kurulumu",
                            IsDeleted = false,
                            Name = "Mart Sprint I",
                            ProjectId = 1,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            State = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Goal = "CRM modül entegrasyonu",
                            IsDeleted = false,
                            Name = "Mart Sprint II",
                            ProjectId = 1,
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            State = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Goal = "Test ve go-live hazırlığı",
                            IsDeleted = false,
                            Name = "Nisan Sprint I",
                            ProjectId = 1,
                            StartDate = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            State = 0
                        });
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.TaskStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosedStage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInKanban")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskStages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Yapılacak",
                            ProjectId = 1,
                            ShowInKanban = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Analiz",
                            ProjectId = 1,
                            ShowInKanban = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Devam Etmekte",
                            ProjectId = 1,
                            ShowInKanban = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Test Yapmak",
                            ProjectId = 1,
                            ShowInKanban = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = true,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Bitti",
                            ProjectId = 1,
                            ShowInKanban = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Yapılacak",
                            ProjectId = 2,
                            ShowInKanban = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Analiz",
                            ProjectId = 2,
                            ShowInKanban = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Devam Etmekte",
                            ProjectId = 2,
                            ShowInKanban = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Test Yapmak",
                            ProjectId = 2,
                            ShowInKanban = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = true,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Bitti",
                            ProjectId = 2,
                            ShowInKanban = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Yapılacak",
                            ProjectId = 3,
                            ShowInKanban = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Analiz",
                            ProjectId = 3,
                            ShowInKanban = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Devam Etmekte",
                            ProjectId = 3,
                            ShowInKanban = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Test Yapmak",
                            ProjectId = 3,
                            ShowInKanban = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = true,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Bitti",
                            ProjectId = 3,
                            ShowInKanban = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Yapılacak",
                            ProjectId = 4,
                            ShowInKanban = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Analiz",
                            ProjectId = 4,
                            ShowInKanban = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Devam Etmekte",
                            ProjectId = 4,
                            ShowInKanban = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Test Yapmak",
                            ProjectId = 4,
                            ShowInKanban = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = true,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Bitti",
                            ProjectId = 4,
                            ShowInKanban = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Yapılacak",
                            ProjectId = 5,
                            ShowInKanban = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Analiz",
                            ProjectId = 5,
                            ShowInKanban = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Devam Etmekte",
                            ProjectId = 5,
                            ShowInKanban = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Test Yapmak",
                            ProjectId = 5,
                            ShowInKanban = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = true,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Bitti",
                            ProjectId = 5,
                            ShowInKanban = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Yapılacak",
                            ProjectId = 6,
                            ShowInKanban = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Analiz",
                            ProjectId = 6,
                            ShowInKanban = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Devam Etmekte",
                            ProjectId = 6,
                            ShowInKanban = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Test Yapmak",
                            ProjectId = 6,
                            ShowInKanban = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = true,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Bitti",
                            ProjectId = 6,
                            ShowInKanban = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Yapılacak",
                            ProjectId = 7,
                            ShowInKanban = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Analiz",
                            ProjectId = 7,
                            ShowInKanban = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Devam Etmekte",
                            ProjectId = 7,
                            ShowInKanban = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Test Yapmak",
                            ProjectId = 7,
                            ShowInKanban = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = true,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Bitti",
                            ProjectId = 7,
                            ShowInKanban = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Yapılacak",
                            ProjectId = 8,
                            ShowInKanban = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Analiz",
                            ProjectId = 8,
                            ShowInKanban = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Devam Etmekte",
                            ProjectId = 8,
                            ShowInKanban = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = false,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Test Yapmak",
                            ProjectId = 8,
                            ShowInKanban = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsClosedStage = true,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Bitti",
                            ProjectId = 8,
                            ShowInKanban = true,
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Yazılım",
                            Email = "buse.karapinar@pentahub.com",
                            FullName = "Buse Karapınar",
                            IsActive = true,
                            IsDeleted = false,
                            Role = "ProjectManager"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Satış",
                            Email = "can.atem@pentahub.com",
                            FullName = "Can Atem",
                            IsActive = true,
                            IsDeleted = false,
                            Role = "ProjectManager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Yazılım",
                            Email = "osman.kaya@pentahub.com",
                            FullName = "Osman Kaya",
                            IsActive = true,
                            IsDeleted = false,
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            Email = "ali.akin@pentahub.com",
                            FullName = "Ali Akın",
                            IsActive = true,
                            IsDeleted = false,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Pazarlama",
                            Email = "gizem.ciger@pentahub.com",
                            FullName = "Gizem Çiğer",
                            IsActive = true,
                            IsDeleted = false,
                            Role = "ProjectManager"
                        });
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.Project", b =>
                {
                    b.HasOne("PentaHub.Domain.Entities.User", "ProjectManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.ProjectTask", b =>
                {
                    b.HasOne("PentaHub.Domain.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PentaHub.Domain.Entities.ProjectTask", "ParentTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PentaHub.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PentaHub.Domain.Entities.Sprint", "Sprint")
                        .WithMany("Tasks")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PentaHub.Domain.Entities.TaskStage", "Stage")
                        .WithMany("Tasks")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("ParentTask");

                    b.Navigation("Project");

                    b.Navigation("Sprint");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.Sprint", b =>
                {
                    b.HasOne("PentaHub.Domain.Entities.Project", "Project")
                        .WithMany("Sprints")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.TaskStage", b =>
                {
                    b.HasOne("PentaHub.Domain.Entities.Project", "Project")
                        .WithMany("TaskStages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.Project", b =>
                {
                    b.Navigation("Sprints");

                    b.Navigation("TaskStages");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.ProjectTask", b =>
                {
                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.Sprint", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.TaskStage", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.User", b =>
                {
                    b.Navigation("ManagedProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
