// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PentaHub.Infrastructure.Data;

#nullable disable

namespace PentaHub.Infrastructure.Migrations
{
    [DbContext(typeof(PentaHubDbContext))]
    [Migration("20260327201146_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("PentaHub.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerEvaluation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluationFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBillable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrivacyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("IX_Projects_ContactId");

                    b.HasIndex("ProjectManagerId")
                        .HasDatabaseName("IX_Projects_ProjectManagerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Projects_Status");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "Yazılım",
                            Description = "Acme firmasının dijital dönüşüm süreçlerinin yönetimi",
                            EndDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "Acme Dijital Dönüşüm Projesi",
                            PrivacyLevel = 2,
                            ProjectManagerId = 1,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "Satış",
                            Description = "Müşteri ilişkileri yönetimi sistemi kurulumu",
                            EndDate = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "CRM İmplementasyon",
                            PrivacyLevel = 1,
                            ProjectManagerId = 2,
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "Yazılım",
                            Description = "iOS ve Android platformları için mobil uygulama",
                            EndDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "Mobil Uygulama Geliştirme",
                            PrivacyLevel = 0,
                            ProjectManagerId = 1,
                            StartDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "IT",
                            Description = "Mevcut ERP sistemi ile e-ticaret platformu entegrasyonu",
                            EndDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "E-Ticaret Platform Entegrasyonu",
                            PrivacyLevel = 1,
                            ProjectManagerId = 5,
                            StartDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "İK",
                            Description = "Şirket içi eğitim ve sertifikasyon platformu",
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = false,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "İç Eğitim Portalı",
                            PrivacyLevel = 1,
                            ProjectManagerId = 5,
                            StartDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "IT",
                            Description = "Legacy veri ambarının bulut tabanlı çözüme taşınması",
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = false,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "Veri Ambarı Modernizasyonu",
                            PrivacyLevel = 0,
                            ProjectManagerId = 4,
                            StartDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "Yazılım",
                            Description = "Müşteri self-servis portalının yeniden tasarlanması",
                            EndDate = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = true,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "Müşteri Portalı Yenileme",
                            PrivacyLevel = 2,
                            ProjectManagerId = 2,
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEvaluation = 0,
                            DepartmentName = "Pazarlama",
                            Description = "Marketing automation araçlarının entegrasyonu ve kampanya yönetimi",
                            EndDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBillable = false,
                            IsDeleted = false,
                            IsTemplate = false,
                            Name = "Pazarlama Otomasyon Projesi",
                            PrivacyLevel = 1,
                            ProjectManagerId = 5,
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        });
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Yazılım",
                            Email = "buse.karapinar@pentahub.com",
                            FullName = "Buse Karapınar",
                            IsActive = true,
                            IsDeleted = false,
                            Role = "ProjectManager"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Satış",
                            Email = "can.atem@pentahub.com",
                            FullName = "Can Atem",
                            IsActive = true,
                            IsDeleted = false,
                            Role = "ProjectManager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Yazılım",
                            Email = "osman.kaya@pentahub.com",
                            FullName = "Osman Kaya",
                            IsActive = true,
                            IsDeleted = false,
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            Email = "ali.akin@pentahub.com",
                            FullName = "Ali Akın",
                            IsActive = true,
                            IsDeleted = false,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Pazarlama",
                            Email = "gizem.ciger@pentahub.com",
                            FullName = "Gizem Çiğer",
                            IsActive = true,
                            IsDeleted = false,
                            Role = "ProjectManager"
                        });
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.Project", b =>
                {
                    b.HasOne("PentaHub.Domain.Entities.User", "ProjectManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("PentaHub.Domain.Entities.User", b =>
                {
                    b.Navigation("ManagedProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
