using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using PentaHub.Application.Tasks.Commands.CreateTask;
using PentaHub.Application.Tasks.Commands.DeleteTask;
using PentaHub.Application.Tasks.Commands.MoveTaskStage;
using PentaHub.Application.Tests.Common;

namespace PentaHub.Application.Tests.Tasks;

public class TaskCommandTests : IDisposable
{
    private readonly TestFixture _fixture;

    public TaskCommandTests()
    {
        _fixture = new TestFixture();
    }

    [Fact]
    public async Task Should_CreateTask_WithAutoGeneratedTaskNumber()
    {
        // Arrange — Project 1 already has seeded tasks T0001 and T0002
        var command = new CreateTaskCommand
        {
            Title = "New Task From Test",
            Description = "Task created via integration test",
            ProjectId = TestFixture.ProjectId1,
            AssigneeId = TestFixture.UserId1,
            Priority = 2, // Medium
            IsBillable = true,
            PlannedHours = 8
        };

        // Act
        var result = await _fixture.Mediator.Send(command);

        // Assert
        result.Should().NotBeNull();
        result.Id.Should().BeGreaterThan(0);
        result.Title.Should().Be("New Task From Test");
        result.TaskNumber.Should().NotBeNullOrEmpty();
        result.TaskNumber.Should().StartWith("T");
        // Next sequential number after T0002 is T0003
        result.TaskNumber.Should().Be("T0003");
        result.ProjectId.Should().Be(TestFixture.ProjectId1);
        result.PlannedHours.Should().Be(8);
        result.RemainingHours.Should().Be(8);
        result.SubTaskCount.Should().Be(0);
    }

    [Fact]
    public async Task Should_CreateTask_InProjectWithNoTasks_GeneratesT0001()
    {
        // Arrange — Project 2 has no seeded tasks
        var command = new CreateTaskCommand
        {
            Title = "First Task in Project 2",
            ProjectId = TestFixture.ProjectId2,
            Priority = 0,
            PlannedHours = 4
        };

        // Act
        var result = await _fixture.Mediator.Send(command);

        // Assert
        result.Should().NotBeNull();
        result.TaskNumber.Should().Be("T0001");
        result.ProjectId.Should().Be(TestFixture.ProjectId2);
    }

    [Fact]
    public async Task Should_MoveTask_ToDifferentStage()
    {
        // Arrange — move seeded task 1 (currently in stage StageId_P1_Todo) to StageId_P1_InProgress
        var command = new MoveTaskStageCommand(
            TaskId: TestFixture.TaskId1,
            StageId: TestFixture.StageId_P1_InProgress);

        // Act
        var result = await _fixture.Mediator.Send(command);

        // Assert
        result.Should().BeTrue();

        var context = _fixture.DbContext;
        var task = await context.ProjectTasks.FirstAsync(t => t.Id == TestFixture.TaskId1);
        task.StageId.Should().Be(TestFixture.StageId_P1_InProgress);
    }

    [Fact]
    public async Task Should_ThrowKeyNotFoundException_WhenMovingToNonExistentStage()
    {
        // Arrange
        var command = new MoveTaskStageCommand(TaskId: TestFixture.TaskId1, StageId: 9999);

        // Act
        var act = () => _fixture.Mediator.Send(command);

        // Assert
        await act.Should().ThrowAsync<KeyNotFoundException>()
            .WithMessage("*9999*");
    }

    [Fact]
    public async Task Should_SoftDeleteTask_WhenDeleted()
    {
        // Arrange
        var command = new DeleteTaskCommand(TestFixture.TaskId1);

        // Act
        var result = await _fixture.Mediator.Send(command);

        // Assert
        result.Should().BeTrue();

        // Verify IsDeleted flag was set
        var context = _fixture.DbContext;
        var deletedTask = await context.ProjectTasks
            .IgnoreQueryFilters()
            .FirstOrDefaultAsync(t => t.Id == TestFixture.TaskId1);

        deletedTask.Should().NotBeNull();
        deletedTask!.IsDeleted.Should().BeTrue();
    }

    [Fact]
    public async Task Should_ThrowKeyNotFoundException_WhenDeletingNonExistentTask()
    {
        // Arrange
        var command = new DeleteTaskCommand(9999);

        // Act
        var act = () => _fixture.Mediator.Send(command);

        // Assert
        await act.Should().ThrowAsync<KeyNotFoundException>()
            .WithMessage("*9999*");
    }

    public void Dispose() => _fixture.Dispose();
}
